// TODO: Properly consolidate this with server error codes

export enum ErrorCode {
  // Client errors (4xx)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_INPUT = 'INVALID_INPUT',

  // Server errors (5xx)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',

  // WebSocket specific errors
  WEBSOCKET_MESSAGE_ERROR = 'WEBSOCKET_MESSAGE_ERROR',

  // Game specific errors
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_FULL = 'ROOM_FULL',
  GAME_NOT_ACTIVE = 'GAME_NOT_ACTIVE',
  INVALID_GAME_STATE = 'INVALID_GAME_STATE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  USER_ALREADY_IN_ROOM = 'USER_ALREADY_IN_ROOM',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  KICKED_FROM_ROOM = 'KICKED_FROM_ROOM'
}
